language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  yarn: true
jobs:
  include:
  - stage: test
    name: Unit tests
    script: ./scripts/test.sh
  - stage: deploy
    name: Deploy and Build
    script: ./scripts/deploy.sh
    install: true
stages:
- test
- deploy