language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  yarn: true
jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: ./unit-test
    - stage: build-and-deploy
      name: "Build and Deploy"
      script: yarn build && echo 'Deploy placeholder'
stages:
  - test
  - build-and-deploy
