language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  yarn: true
jobs:
  include:
  - stage: test
    name: Unit tests
    script: yarn test
  - stage: deploy
    name: Deploy and Build
    script: ./scripts/deploy.sh
stages:
- test
- deploy
before_install:
- openssl aes-256-cbc -K $encrypted_7e8b61df6307_key -iv $encrypted_7e8b61df6307_iv
  -in nikoyan-rsa.enc -out nikoyan-rsa -d
