language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  yarn: true
jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: ./unit-test
    - stage: build
      script: ./build
    - stage: deploy
      script: ./deploy
stages:
  - test
  - build
  - deploy

unit-test:
  script: yarn test

build:
  script: yarn build

deploy:
  script: echo 'Deploy :)'
